sunxi-disp-brightness: sunxi_disp_brightness.o
	$(CC) sunxi_disp_brightness.o -o sunxi-disp-brightness

.c.o:
	$(CC) -c sunxi_disp_brightness.c

clean:
	rm -f sunxi_disp_brightness.o sunxi-disp-brightness
